version: '3.9'

services:
    redis:
        container_name: redis
        image: redis:7.0
        ports:
        - "6379:6379"

    web:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - redis
        links:
          - redis